# kwplayer.spec
# Used to build rpm for kwplayer on Fedora 21/22/23
# Released by mosquito <sensor.wen@gmail.com>, wangjiezhe <wangjiezhe@gmail.com>
# This spec file is published under the GPLv3 license

# Template is originally generated by "rpmdev-newspec -t python"
%{!?python3_sitelib: %global python3_sitelib %(%{__python3} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")}
%global debug_package %{nil}
%global project kwplayer
%global repo %{project}

# commit
%global _commit d6237336b63b63b613f90bdbbed32f24471be86f
%global _shortcommit %(c=%{_commit}; echo ${c:0:7})

Name:		kwplayer
Version:	3.5.2
Release:	3.git%{_shortcommit}%{?dist}
Summary:	An elegant music player which can get songs from kuwo.cn
Summary(zh_CN):	酷我音乐播放器, 音乐资源从 kuwo.cn 获取

Group:		Applications/Multimedia
License:	GPLv3
URL:		https://github.com/LiuLang/kwplayer
Source:		https://github.com/LiuLang/kwplayer/archive/%{_commit}/%{repo}-%{_shortcommit}.tar.gz

BuildArch:	noarch
BuildRequires:	python3-devel
Requires:	python3-cairo
Requires:	python3-dbus
Requires:	python3-gobject
Requires:	python3-ply
Requires:	gstreamer1-plugins-base
Requires:	gstreamer1-plugins-good
Requires:	gstreamer1-plugins-ugly
Requires:	gstreamer1-libav
Requires:	gstreamer1
Requires:	gstreamer-python
Requires:	libnotify
Requires:	pulseaudio
Requires:	pulseaudio-module-x11
# Not installed by default in KDE
Requires:	gnome-icon-theme-symbolic
# Optional:
Requires:	leveldb
Requires:	python3-plyvel
Requires:	python3-mutagen
Requires:	python3-keybinder
Requires:	python3-html2text

%description
KW music player is used to get music resources from Internet.
It can also play MV, show lyrics and show photo albums of artists.

%description -l zh_CN
KW 音乐播放器的音乐资源从网络获取.
除了音乐播放, 还可以播放 MV, 显示桌面歌词, 及专辑封面.

%prep
%setup -q -n %repo-%{_commit}

%build
%{__python3} setup.py build

%install
%{__python3} setup.py install -O1 --skip-build --root=%{buildroot}

cat > %{buildroot}%{_datadir}/applications/%{name}.desktop << EOF
[Desktop Entry]
Name=Kuwo Player
GenericName=Kuwo Player
Comment=Play music from Internet
Name[zh_CN]=酷我音乐
GenericName[zh_CN]=酷我音乐
Comment[zh_CN]=酷我音乐 linux 客户端
Name[zh_TW]=酷我音乐
GenericName[zh_TW]=KW 音乐
Comment[zh_TW]=酷我音乐 linux 客户端
Type=Application
Exec=kwplayer
Icon=kwplayer
StartupNotify=true
Terminal=false
Categories=AudioVideo;Player;GTK;
EOF

%find_lang %{name}

%post
/bin/touch --no-create %{_datadir}/icons/hicolor &>/dev/null ||:
/usr/bin/gtk-update-icon-cache -f -t -q %{_datadir}/icons/hicolor ||:
/usr/bin/update-desktop-database -q ||:

%postun
if [ $1 -eq 0 ]; then
    /bin/touch --no-create %{_datadir}/icons/hicolor &>/dev/null ||:
    /usr/bin/gtk-update-icon-cache -f -t -q %{_datadir}/icons/hicolor ||:
fi
/usr/bin/update-desktop-database -q ||:

%files -f %{name}.lang
%doc README.md HISTORY
%license LICENSE
%{_bindir}/%{name}
%{_datadir}/icons/hicolor/*
%{_datadir}/kwplayer/icons/*
%{_datadir}/applications/%{name}.desktop
%{python3_sitelib}/kuwo/*
%{python3_sitelib}/%{name}-%{version}-py%{python3_version}.egg-info

%changelog
* Sun Dec 13 2015 mosquito <sensor.wen@gmail.com> - 3.5.2-3.gitd623733
- Update post script
* Thu Sep 24 2015 mosquito <sensor.wen@gmail.com> - 3.5.2-2.gitd623733
- Update to 3.5.2-2.gitd623733
* Wed May 06 2015 mosquito <sensor.wen@gmail.com> - 3.5.2-1.gitfceb0a3
- Rename version name
* Fri Jan 23 2015 mosquito <sensor.wen@gmail.com> - 3.5.1git20150122-1
- Update version to 3.5.1git20150122
* Mon Jan 12 2015 mosquito <sensor.wen@gmail.com> - 3.5.1git20150109-1
- Update version to 3.5.1git20150109
* Wed Jan 07 2015 mosquito <sensor.wen@gmail.com> - 3.4.9git20150105-1
- Update version to 3.4.9git20150105
* Sat Jan 03 2015 mosquito <sensor.wen@gmail.com> - 3.4.9git20150102-1
- Update version to 3.4.9git20150102
* Thu Jan 01 2015 mosquito <sensor.wen@gmail.com> - 3.4.9git20141231-1
- Update version to 3.4.9git20141231
* Mon Dec 15 2014 mosquito <sensor.wen@gmail.com> - 3.4.8git20141214-1
- Update version to 3.4.8git20141214
* Tue Dec 09 2014 mosquito <sensor.wen@gmail.com> - 3.4.8git20141209-1
- Update version to 3.4.8git20141209
* Sun Dec 07 2014 mosquito <sensor.wen@gmail.com> - 3.4.8git20141206-1
- Update version to 3.4.8git20141206
* Wed Dec 03 2014 mosquito <sensor.wen@gmail.com> - 3.4.6git20141130-1
- Update version to 3.4.6git20141130
* Tue Nov 18 2014 mosquito <sensor.wen@gmail.com> - 3.4.6git20141118-1
- Update version to 3.4.6git20141118
* Mon Nov 17 2014 mosquito <sensor.wen@gmail.com> - 3.4.6git20141117-1
- Initial build
